#!/bin/bash
#
# Tools manage your attract-mode installation

source "$(dirname $BASH_SOURCE)/lib/system.sh"
source "$(dirname $BASH_SOURCE)/lib/utils.sh"
source "$(dirname $BASH_SOURCE)/lib/attract.sh"

readonly HELP=$(cat <<EOF
  Usage: attract-tool --action

  Actions:
    --help: display help message
    --generate-mame-emulator-config: generate the emulator config file for MAME
EOF
)

display_help() {
  echo "$HELP"
  exit 0
}

if [[ -z "$1" ]]; then display_help; fi

for command in $@; do
  if [[ "$command" == "--help" ]]; then display_help; fi

  command_name=$(echo "${command:2}" | tr - _)
  if [[ "${command:0:2}" == "--" ]]; then
    attract_$command_name
  fi
done