#!/bin/bash
#
# Bootstrap the Host to build an Arcade game cab

readonly LIBDIR=$(if [[ -d /vagrant ]]; then echo /vagrant/lib; else echo $(dirname $BASH_SOURCE)/lib; fi)
readonly ARTWORK_DIR=$(if [[ -d /vagrant ]]; then echo /vagrant/artwork; else echo $(dirname $BASH_SOURCE)/artwork; fi)

source "$LIBDIR/system.sh"
source "$LIBDIR/utils.sh"
source "$LIBDIR/attract.sh"

readonly USER="arcade"
readonly KEYBOARD="us"
readonly SCREEN_RESOLUTION="1024x768"
readonly BOOTSPLASH_IMAGE_PATH="$ARTWORK_DIR/bootloader.png"

configure_bootsplash() {
  build_plymouth_theme "/usr/share/plymout/themes" "arcade" $BOOTSPLASH_IMAGE_PATH
  setup_bootsplash "arcade" $SCREEN_RESOLUTION
  set_grub_timeout 0
}

configure_audio() {
  setup_audio
}

configure_arcade_user() {
  create_user $USER
  login_on_startup_user $USER
  setup_x_server $USER $SCREEN_RESOLUTION $KEYBOARD
  startx_on_login $USER
}

configure_attract_mode() {
  attract_install_package
  start_on_startx $USER "attract"
}

main() {
  update_system
  configure_audio
  configure_bootsplash
  configure_arcade_user
  configure_attract_mode
  reboot
}

main
