#!/bin/bash
#
# Tools manage your mame installation

source "$(dirname $BASH_SOURCE)/lib/system.sh"
source "$(dirname $BASH_SOURCE)/lib/utils.sh"
source "$(dirname $BASH_SOURCE)/lib/mame.sh"

# TODO: --help
for command in $@; do
  command_name=$(echo "${command:2}" | tr - _)
  if [[ "${command:0:2}" == "--" ]]; then
    mame_$command_name
  fi
done